services:
  - type: web
    name: hansa-test
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y poppler-utils tesseract-ocr
      pip install -r requirements.txt
    startCommand: python app.py